import Head from 'next/head';
import Dashboard from './dashboard';
import { getSession, useSession } from 'next-auth/react'
import Login from '../components/Login';

export default function Home() {
  
  // const { data: session } = useSession();

  // if(!session) return <Login />


  return (
    <div >
      <Head>
        <title>Revamp AI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <div>
      <Dashboard/>
      </div> 
      
    </div>
  );
}

// export async function getServerSideProps(context) {
//   const session = await getSession(context);

//   return {
//     props: {
//       session
//     }
//   }
// }