import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Dashboard from './dashboard'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Revamp AI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css"/>
      </Head>
      <div>
      <Dashboard/>
      </div> 
      
    </div>
  )
}
